const PENDING_PAYMENT = "PENDING_PAYMENT";
const PAID = "PAID";
const CANCELED = "CANCELED";
const MIDTRANS_SERVER_KEY = process.env.MIDTRANS_SERVER_KEY;
const MIDTRANS_APP_URL = process.env.MIDTRANS_APP_URL;
const FRONT_END_URL = process.env.FRONT_END_URL;

module.exports = {
  PENDING_PAYMENT,
  PAID,
  CANCELED,
  MIDTRANS_SERVER_KEY,
  MIDTRANS_APP_URL,
  FRONT_END_URL,
};
